### ISSUE TITLE
[Feature Request] Support transfer token to a given addr

### ISSUE THREAD

**Issue by raullenchai** [siyushin/_mintToken#5]
<img width="698" alt="Screen Shot 2020-10-14 at 9 00 22 AM" src="https://user-images.githubusercontent.com/989846/96014945-d10a5600-0dfb-11eb-9e2a-5b60f0970d72.png">

The minted tokens are all in the minter's addr. Support send tokens to a given account on this page.

**Comment by siyushin** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/181870/96092236-309c5a80-0efd-11eb-9ca3-5a2c03b616bd.png">
