### ISSUE TITLE
[Feature Request] Support `Mint To` a given addr

### ISSUE THREAD

**Issue by raullenchai** [siyushin/_mintToken#6]
<img width="637" alt="Screen Shot 2020-10-14 at 9 02 40 AM" src="https://user-images.githubusercontent.com/989846/96015107-0747d580-0dfc-11eb-9caa-21608c6d2037.png">

We should support minting an NFT and assign it to a given addr

**Comment by siyushin** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/181870/96092417-6e00e800-0efd-11eb-8218-3fb087d717e6.png">

Done.
